development:
  adapter: postgresql
  database: toptal_eugenek_dev
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: toptal_eugenek_test
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: toptal_eugenek_production
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
